---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
 name: test-pipeline-simple
 namespace: test
 labels:
   pipelines.appstudio.openshift.io/type: test
spec:
 pipelineSpec:
   tasks:
      - name: log-generation
        taskSpec:
          metadata:
            labels:
              app: "simple-log"
          steps:
            - name: generate-random-echo
              image: registry.access.redhat.com/ubi9/ubi
              script: |
                #!/usr/bin/env bash
                cat /dev/urandom | tr -dc '[:alpha:]' | fold -w ${1:-20} | head -n 5
