apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tests
  namespace: default
  labels:
    pipelines.appstudio.openshift.io/type: test
    pipelines.appstudio.openshift.io/workspace_id: "12345678"
    pipelines.appstudio.openshift.io/workspace_name: "ws_1"
spec:
  pipelineSpec:
    tasks:
      - name: log-generation
        taskSpec:
          metadata:
            labels:
              app: "example"
          steps:
            - name: generate-log
              image: registry.access.redhat.com/ubi9/ubi
              script: |
                mkdir -p /tests
                echo "Starting LOG Generation!"
                head -c 1G < /dev/urandom > /tests/random-data.log || exit 1
                if [ ! -f /tests/random-data.log ]; then
                  echo "File Not Found"
                  exit 1
                fi
                ls -lh /tests/random-data.log
                echo "Log Generation completed"
              resources:
                requests:
                  memory: 1Gi
                  cpu: 500m
                limits:
                  memory: 2Gi
                  cpu: 4000m
