kind: Service
apiVersion: v1
metadata:
  name: node-exporter-service 
  namespace: openshift-monitoring 
  labels:
    servicetype: metrics 
spec:
  ports:
    - name: exmet 
      protocol: TCP
      port: 9100 
      targetPort: 9100 
  type: ClusterIP
  selector:
    monitor: metrics 
